### ISSUE TITLE
readme.md is less informative about the project

### ISSUE THREAD

**Issue by Anuraj-IND** [WyriHaximus/php-cpu-core-detector#92]
Can you tell me funtionality i can create a codeOfconduct.md and update readme.md for contributors so they can understand about your project more easily also if you can assign me this issue please add label of hacktoberfest and gssoc im new just looking to do some contributions

**Comment by Anuraj-IND** [comment]
@WyriHaximus you still need to tell me about your project and its funtion

**Comment by WyriHaximus** [comment]
@Anuraj-IND Correct got sidetracked yesterday.

So for the readme include both examples from the examples directory and refer to it with a markdown link.

Never done a codeofconduct.md before so give your best shot for it.

What is the gssoc label for, can you point me to their event website?

**Comment by Anuraj-IND** [comment]
@WyriHaximus https://gssoc.girlscript.tech/project the website you asked for and i did the pull request see

**Comment by Anuraj-IND** [comment]
@WyriHaximus check pull request I did what I can for now and yea thanks for letting me contribute in your project it was my first time and I never contributed to a big project like that irl lol thanks

**Comment by Anuraj-IND** [comment]
@WyriHaximus can you accept my pr today october is about to end..

**Comment by WyriHaximus** [comment]
@Anuraj-IND Done, next time chill no need to push this hard. And hope you learned something here

**Comment by Anuraj-IND** [comment]
> @Anuraj-IND Done, next time chill no need to push this hard. And hope you learned something here

I mean @WyriHaximus I did my job right only thing was squash stuff which I never did I did rephase to sync my commits except that I didn't pushed myself and yea I learnt linking and half way through squash thanks for that too it was fun and stressful at same time lol btw HAPPY DIWALI 🪔 🎇

**Comment by WyriHaximus** [comment]
> > @Anuraj-IND Done, next time chill no need to push this hard. And hope you learned something here
> 
> I mean @WyriHaximus I did my job right only thing was squash stuff which I never did I did rephase to sync my commits except that I didn't pushed myself and yea I learnt linking and half way through squash thanks for that too it was fun and stressful at same time lol btw HAPPY DIWALI 🪔 🎇

There are a lot of things to this job, been doing it close to two decades at this point. Writing code is one of them, there is communication, knowing your toolkit, and many more. It takes time to build those skills, for me getting the rebase in so the commit history is clean is part of the job. At the same time I recognize you're still learning so instead of demanding you must do it and completely or no merge I made sure to write out every step for you. And when that didn't work out as we both wanted and both got frustrated by it, I did it to make sure this ended on a positive note for both of us. Personally, I'm currently working on getting better at teaching/mentoring when there is a language and/or cultural barrier. So yes I'm happy to hear you learned something and had fun, even though it was stressful at times those always tended the moments I learned the most. Happy Diwali!
